name: Build Adolf NameTag

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Check files
        run: |
          echo "Repository:"
          dir
          echo "Libs:"
          dir libs

      - name: Build
        run: dotnet build AdolfNameTag.csproj --configuration Release
